apiVersion: v1
kind: Service
metadata:
  name: hello-world-flask
  namespace: default
  annotations:
    cloud.google.com/app-protocols: '{"my-https-port":"HTTPS","my-http-port":"HTTP"}'
spec:
  type: NodePort
  selector:
    app: hello-world-flask
  ports:
    - name: my-http-port
      protocol: TCP
      port: 80
      targetPort: 5000
    - name: my-https-port
      protocol: TCP
      port: 443
      targetPort: 8443
